# This file contains values from Cookiecutter

default_context:
  project_name: "wifi-qr-generator"
  project_description: "A streamlit app to generate WiFi QR codes"
  organization: "jga-streamlit-apps"
  license: "MIT"
  minimal_python_version: 3.11
  github_name: "jga-streamlit-apps"
  email: "jakob1379@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
